global:
  namespace: production
frontend:
  replicaCount: 2
  image:
    tag: v0.2.0
    shaTag: prod-3b0db0e
authService:
  replicaCount: 2
  image:
    tag: v0.2.0
    shaTag: prod-3b0db0e
assessmentService:
  replicaCount: 2
  image:
    tag: v0.2.0
    shaTag: prod-3b0db0e
therapistService:
  replicaCount: 2
  image:
    tag: v0.2.0
    shaTag: prod-3b0db0e
