global:
  namespace: production
frontend:
  replicaCount: 2
  image:
    tag: v0.2.2
    shaTag: prod-2dfa90e
authService:
  replicaCount: 2
  image:
    tag: v0.2.2
    shaTag: prod-2dfa90e
assessmentService:
  replicaCount: 2
  image:
    tag: v0.2.2
    shaTag: prod-2dfa90e
therapistService:
  replicaCount: 2
  image:
    tag: v0.2.2
    shaTag: prod-2dfa90e
