apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    environment: {{ .Values.global.namespace }}
    managed-by: helm
    app.kubernetes.io/managed-by: Helm
