apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calmroot-jwt-external-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.secrets.jwt.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.secrets.jwt.dataKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.jwt.remoteRefKey }}
        property: {{ .Values.externalSecrets.secrets.jwt.dataKey }}
