apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calmroot-ses-external-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.secrets.ses.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: SES_SENDER_EMAIL
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.ses.remoteRefKey }}
        property: SES_SENDER_EMAIL
    - secretKey: SMTP_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.ses.remoteRefKey }}
        property: SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.ses.remoteRefKey }}
        property: SMTP_PORT
    - secretKey: SMTP_USER
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.ses.remoteRefKey }}
        property: SMTP_USER
    - secretKey: SMTP_PASS
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.ses.remoteRefKey }}
        property: SMTP_PASS
    - secretKey: SMTP_FROM
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.ses.remoteRefKey }}
        property: SMTP_FROM
