apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.assessmentService.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: assessment-service
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.assessmentService.serviceAccount.roleArn | quote }}
