apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: assessment-service
spec:
  selector:
    app: assessment-service
  ports:
    - protocol: TCP
      port: {{ .Values.assessmentService.port }}
      targetPort: {{ .Values.assessmentService.port }}
  type: ClusterIP
