apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: calmroot
  namespace: argocd
spec:
  description: CalmRoot Mental Health Platform
  sourceRepos:
    - https://github.com/CalmRoot/gitops.git
  destinations:
    - namespace: production
      server: https://kubernetes.default.svc
    - namespace: development
      server: https://kubernetes.default.svc
    - namespace: envoy-gateway-system
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
