apiVersion: v1
kind: Service
metadata:
  name: therapist-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: therapist-service
spec:
  selector:
    app: therapist-service
  ports:
    - protocol: TCP
      port: {{ .Values.therapistService.port }}
      targetPort: {{ .Values.therapistService.port }}
  type: ClusterIP
